name: Migrate Nx workspace

concurrency:
  group: nx-migrate@${{ github.ref_name }}
  cancel-in-progress: false

on:
  push:
    branches:
      - renovate/nx-migrate
  workflow_dispatch:
    branches:
      - renovate/nx-migrate

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  migrate:
    name: Migrate Nx workspace
    # if: ${{ github.event_name == 'workflow_dispatch' || contains(fromJSON('["bot@renovateapp.com", "29139614+renovate[bot]@users.noreply.github.com"]'), github.event.head_commit.author.email) }}
    runs-on: ubuntu-latest

    outputs:
      commit-hash: ${{ steps.output.outputs.commit-hash }}

    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      - name: Fetch base branch
        run: git fetch origin main --depth=1
      - name: Check out base branch
        run: git switch main
      - name: Check out head branch
        run: git checkout -

      - name: Set up Node.js and install dependencies
        uses: ./.github/actions/setup-node
      - name: Install package dependencies
        run: yarn install --no-interactive

      - name: Debug Nx
        run: yarn nx report

      - name: Migrate Nx workspace
        run: yarn nx run tools:migrate-nx

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "feat(deps): migrate Nx-managed dependencies"
          git push

      - name: Output commit hash
        id: output
        run: echo "::set-output name=commit-hash::$(git rev-parse --verify HEAD)"

  automerge:
    name: Automerge
    if: ${{ needs.migrate.result == 'success' }}
    needs: migrate
    runs-on: ubuntu-latest

    steps:
      - name: Wait for jobs to succeed
        uses: lewagon/wait-on-check-action@v1.1.1
        with:
          check-regexp: '@await'
          ref: ${{ needs.migrate.outputs.commit-hash }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Ignore check for this job
          running-workflow-name: Automerge

      - name: Check out source code
        uses: actions/checkout@v2
      - name: Enable automerge
        run: gh pr merge --squash --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
